#install:: version
#//all: mac
#//   rm -rf dad *.o

main.o: dad.cpp
	g++ -o dad dad.cpp

#	cd /Users/ilya/Library/Developer/Xcode/DerivedData/LabWork_4-awkuwxdemmmhxgfxzanfgfzwfqea/Build/Products/Debug/Dad
#	./Dad
